load "CFN_Networks.m2"


-- set number of leaves and model
n = 5
M = CFNmodel


-- setup the ring and compute the vanishing ideal of the CFN model on the standard 4-sunlet
-- by results of https://arxiv.org/pdf/2312.07450, the ideal is generated by quadratics 
-- so it suffices to compute all quadratic generators of the kernel of the corresponding ring map
S = qRing(n, M);
images = sunletParam(n, M);
R = ring images_0;
phi = map(R, S, images);
H = componentsOfKernel(2, phi);
I = ideal delete(null, flatten values H)


-- compute the vanishing ideal of the tree with FourTiTwo
T = leafTree({1,2,3,4,5}, {{2, 3}, {1, 2, 3}})
J = sub(phyloToric42(T, CFNmodel), ring I)


-- check that I_N and I_T are mutually not contained
isSubset(I, J)
isSubset(J, I)